#ifndef MP_LOGGER_CONSTANTS_H
#define MP_LOGGER_CONSTANTS_H

#define MP_LOGGER_NAME_CAPACITY 64u
#define MP_LOGGER_PATH_CAPACITY 256u
#define MP_LOGGER_ACTIVE_STREAMS_CAPACITY 128u
#define MP_LOGGER_HOST_CAPACITY 128u
#define MP_LOGGER_MAX_STREAMS 8u
#define MP_LOGGER_TIMESTAMP_CAPACITY 32u
#define MP_LOGGER_RENDER_PADDING 384u
#define MP_LOGGER_STREAM_NAME_CAPACITY 32u
#define MP_LOGGER_RUN_SUFFIX_CAPACITY 32u
#define MP_LOGGER_UDP_PORT_TEXT_CAPACITY 16u
#define MP_LOGGER_UDP_ENDPOINT_EXTRA_CAPACITY 16u
#define MP_LOGGER_NUMBER_TEXT_CAPACITY 64u
#define MP_LOGGER_SEQUENCE_TEXT_CAPACITY 32u
#define MP_LOGGER_JSON_UNICODE_ESCAPE_CAPACITY 7u
#define MP_LOGGER_DROP_MESSAGE_CAPACITY 128u
#define MP_LOGGER_STREAM_ERROR_MESSAGE_CAPACITY 160u
#define MP_LOGGER_BACKUP_LINE_CAPACITY 512u
#define MP_LOGGER_BOOTSTRAP_LINE_CAPACITY 512u
#define MP_LOGGER_BOOTSTRAP_SECTION_CAPACITY 32u
#define MP_LOGGER_BOOTSTRAP_KEY_CAPACITY 64u
#define MP_LOGGER_BOOTSTRAP_VALUE_CAPACITY 256u

#define MP_LOGGER_DEFAULT_SERVICE_NAME "mp-service"
#define MP_LOGGER_DEFAULT_ENVIRONMENT_NAME "development"
#define MP_LOGGER_DEFAULT_BUFFER_CAPACITY 1024u
#define MP_LOGGER_DEFAULT_MESSAGE_CAPACITY 512u
#define MP_LOGGER_DEFAULT_CONTEXT_CAPACITY 1024u
#define MP_LOGGER_DEFAULT_FIELD_CAPACITY 8u
#define MP_LOGGER_DEFAULT_FIELD_KEY_CAPACITY 32u
#define MP_LOGGER_DEFAULT_FIELD_VALUE_CAPACITY 128u
#define MP_LOGGER_DEFAULT_PRETTY_OUTPUT 0
#define MP_LOGGER_DEFAULT_LOG_DIRECTORY "."
#define MP_LOGGER_DEFAULT_FILE_NAME_PREFIX "mp-service"
#define MP_LOGGER_DEFAULT_BACKUP_FILE_NAME_PREFIX "mp-logger-internal"
#define MP_LOGGER_DEFAULT_ACTIVE_STREAMS "stdout,stderr,file"
#define MP_LOGGER_DEFAULT_UDP_HOST "127.0.0.1"
#define MP_LOGGER_DEFAULT_UDP_PORT 5514u

#define MP_LOGGER_CONFIG_KEY_SERVICE_NAME "service_name"
#define MP_LOGGER_CONFIG_KEY_ENVIRONMENT_NAME "environment_name"
#define MP_LOGGER_CONFIG_KEY_BUFFER_CAPACITY "buffer_capacity"
#define MP_LOGGER_CONFIG_KEY_MESSAGE_CAPACITY "message_capacity"
#define MP_LOGGER_CONFIG_KEY_CONTEXT_CAPACITY "context_capacity"
#define MP_LOGGER_CONFIG_KEY_FIELD_CAPACITY "field_capacity"
#define MP_LOGGER_CONFIG_KEY_FIELD_KEY_CAPACITY "field_key_capacity"
#define MP_LOGGER_CONFIG_KEY_FIELD_VALUE_CAPACITY "field_value_capacity"
#define MP_LOGGER_CONFIG_KEY_FORMAT "format"
#define MP_LOGGER_CONFIG_KEY_PRETTY_OUTPUT "pretty_output"
#define MP_LOGGER_CONFIG_KEY_LOG_DIRECTORY "log_directory"
#define MP_LOGGER_CONFIG_KEY_FILE_NAME_PREFIX "file_name_prefix"
#define MP_LOGGER_CONFIG_KEY_BACKUP_FILE_NAME_PREFIX "backup_file_name_prefix"
#define MP_LOGGER_CONFIG_KEY_ACTIVE_STREAMS "active_streams"
#define MP_LOGGER_CONFIG_KEY_MINIMUM_LEVEL "minimum_level"
#define MP_LOGGER_CONFIG_KEY_MAXIMUM_LEVEL "maximum_level"
#define MP_LOGGER_CONFIG_KEY_HOST "host"
#define MP_LOGGER_CONFIG_KEY_PORT "port"

#define MP_LOGGER_CONFIG_SECTION_ROOT ""
#define MP_LOGGER_CONFIG_SECTION_LOGGER "logger"
#define MP_LOGGER_CONFIG_SECTION_STDOUT "stdout"
#define MP_LOGGER_CONFIG_SECTION_STDERR "stderr"
#define MP_LOGGER_CONFIG_SECTION_FILE "file"
#define MP_LOGGER_CONFIG_SECTION_UDP "udp"

#define MP_LOGGER_STREAM_STDOUT "stdout"
#define MP_LOGGER_STREAM_STDERR "stderr"
#define MP_LOGGER_STREAM_FILE "file"
#define MP_LOGGER_STREAM_UDP "udp"

#define MP_LOGGER_FORMAT_NAME_TEXT "text"
#define MP_LOGGER_FORMAT_NAME_JSON "json"

#define MP_LOGGER_LEVEL_NAME_TRACE "TRACE"
#define MP_LOGGER_LEVEL_NAME_DEBUG "DEBUG"
#define MP_LOGGER_LEVEL_NAME_INFO "INFO"
#define MP_LOGGER_LEVEL_NAME_WARNING "WARNING"
#define MP_LOGGER_LEVEL_NAME_ERROR "ERROR"
#define MP_LOGGER_LEVEL_NAME_FATAL "FATAL"
#define MP_LOGGER_LEVEL_NAME_UNKNOWN "UNKNOWN"
#define MP_LOGGER_LEVEL_TOKEN_TRACE "trace"
#define MP_LOGGER_LEVEL_TOKEN_DEBUG "debug"
#define MP_LOGGER_LEVEL_TOKEN_INFO "info"
#define MP_LOGGER_LEVEL_TOKEN_WARN "warn"
#define MP_LOGGER_LEVEL_TOKEN_WARNING "warning"
#define MP_LOGGER_LEVEL_TOKEN_ERROR "error"
#define MP_LOGGER_LEVEL_TOKEN_FATAL "fatal"

#define MP_LOGGER_STATUS_NAME_OK "OK"
#define MP_LOGGER_STATUS_NAME_QUEUE_FULL "QUEUE_FULL"
#define MP_LOGGER_STATUS_NAME_BUSY "BUSY"
#define MP_LOGGER_STATUS_NAME_INVALID_ARGUMENT "INVALID_ARGUMENT"
#define MP_LOGGER_STATUS_NAME_IO_ERROR "IO_ERROR"
#define MP_LOGGER_STATUS_NAME_CONFIG_ERROR "CONFIG_ERROR"
#define MP_LOGGER_STATUS_NAME_NOT_RUNNING "NOT_RUNNING"
#define MP_LOGGER_STATUS_NAME_INTERNAL_ERROR "INTERNAL_ERROR"
#define MP_LOGGER_STATUS_NAME_LIMIT_EXCEEDED "LIMIT_EXCEEDED"
#define MP_LOGGER_STATUS_NAME_UNKNOWN "UNKNOWN"

#define MP_LOGGER_RENDER_KEY_TIMESTAMP "ts"
#define MP_LOGGER_RENDER_KEY_LEVEL "level"
#define MP_LOGGER_RENDER_KEY_SERVICE "service"
#define MP_LOGGER_RENDER_KEY_ENVIRONMENT "environment"
#define MP_LOGGER_RENDER_KEY_SEQUENCE_ID "sequence_id"
#define MP_LOGGER_RENDER_KEY_MESSAGE "message"
#define MP_LOGGER_RENDER_KEY_CONTEXT "context"

#define MP_LOGGER_BOOL_TRUE "true"
#define MP_LOGGER_BOOL_FALSE "false"
#define MP_LOGGER_BOOL_YES "yes"
#define MP_LOGGER_BOOL_NO "no"
#define MP_LOGGER_BOOL_ONE "1"
#define MP_LOGGER_BOOL_ZERO "0"

#define MP_LOGGER_FILE_EXTENSION ".log"
#define MP_LOGGER_PATH_SEPARATOR "/"
#define MP_LOGGER_FILE_APPEND_MODE "a"
#define MP_LOGGER_FILE_WRITE_MODE "w"
#define MP_LOGGER_FILE_READ_MODE "r"
#define MP_LOGGER_RUN_SUFFIX_FORMAT "%Y%m%dT%H%M%SZ"
#define MP_LOGGER_RUN_SUFFIX_EPOCH "19700101T000000Z"
#define MP_LOGGER_TIMESTAMP_EPOCH "1970-01-01T00:00:00.000Z"
#define MP_LOGGER_TIMESTAMP_FORMAT "%04d-%02d-%02dT%02d:%02d:%02d.%03ldZ"
#define MP_LOGGER_BENCHMARK_CAPTURED_FORMAT "%Y-%m-%d %H:%M:%SZ"

#define MP_LOGGER_BACKUP_SUBSYSTEM "mp_logger"
#define MP_LOGGER_BACKUP_DROPPED_BUSY_MESSAGE "log call contention dropped records total=%llu"
#define MP_LOGGER_BACKUP_DROPPED_FULL_MESSAGE "buffer saturation dropped records total=%llu"
#define MP_LOGGER_BACKUP_WORKER_ALLOC_FAILURE "worker thread could not allocate local buffers"
#define MP_LOGGER_BACKUP_STREAM_WRITE_FAILURE_FORMAT "stream=%s write failure status=%s"
#define MP_LOGGER_BACKUP_BUILTIN_INIT_FAILURE "builtin stream initialization failed"

#endif
